[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Timer Assistant - A text-based timer management application"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller-hooks-contrib>=2025.0",
    "pyinstaller>=6.11.1",
    "word2number>=1.1",
]
