[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller>=6.13.0",
    "pyinstaller-hooks-contrib>=2025.4",
    "word2number>=1.1",
]
